# Generated by Django 5.2.4 on 2025-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
