# Generated by Django 5.2.4 on 2025-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver_current_lat_driver_current_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='current_lng',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
