# Generated by Django 5.2.4 on 2025-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='followup_notes',
            field=models.TextField(blank=True, help_text='Notas de seguimiento y acciones tomadas', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_seguimiento', 'En seguimiento'), ('llamada_conductor', 'Llamada al conductor'), ('llamada_pasajero', 'Llamada al pasajero'), ('llamada_policia', 'Llamada a la policía'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
    ]
