# Generated by Django 5.2.4 on 2025-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_policy_promotion_userpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='target_group',
            field=models.CharField(choices=[('conductor', 'Solo conductores'), ('usuario', 'Solo usuarios/pasajeros'), ('todos', 'Todos')], default='todos', max_length=20),
        ),
    ]
