# Generated by Django 5.2.4 on 2025-07-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_promotion_target_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name_plural': 'Promociones generales'},
        ),
        migrations.AlterModelOptions(
            name='userpromotion',
            options={'verbose_name_plural': 'Promociones personalizadas'},
        ),
    ]
