# Generated by Django 5.2.4 on 2025-07-24 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_earning'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Resumen de Ganancias',
                'verbose_name_plural': 'Resumen de Ganancias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.earning',),
        ),
        migrations.AlterField(
            model_name='earning',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='earning',
            name='description',
            field=models.TextField(blank=True, default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='earning',
            name='earning_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='earning',
            name='related_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.promotion'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='related_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.trip'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_invited_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_trips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
