# Generated by Django 5.2.4 on 2025-07-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Mensaje de chat', 'verbose_name_plural': ' 10. Mensajes de Chat'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 01. Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 02. Driver'},
        ),
        migrations.AlterModelOptions(
            name='earning',
            options={'verbose_name': 'Detalle de Ganancia', 'verbose_name_plural': ' 08. Detalle de Ganancias'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 03. Passenger'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Politicas', 'verbose_name_plural': ' 11. Politicas'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 05. Promociones generales'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 07. Report'},
        ),
        migrations.AlterModelOptions(
            name='resumengananciasproxy',
            options={'verbose_name': 'Resumen de Ganancias', 'verbose_name_plural': ' 09. Resumen de Ganancias'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 04. Trips'},
        ),
        migrations.AlterModelOptions(
            name='userpromotion',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': ' 06. Promociones personalizadas'},
        ),
    ]
